// Generated by CoffeeScript 1.3.3
var Stream;

Stream = require('stream');

/*

`generator([options])`: Generate random CSV data
------------------------------------------------

Options may include
*   duration          Period to run in milliseconds, default to 4 minutes.
*   nb_columns        Number of fields per record
*   max_word_length   Maximum number of characters per word
*   start             Start the generation right away, otherwise call resume
*/


module.exports = function(options) {
  var end, reader, start, _ref, _ref1;
  if (options == null) {
    options = {};
  }
  if ((_ref = options.duration) == null) {
    options.duration = 4 * 60 * 1000;
  }
  options.nb_columns = 8;
  if ((_ref1 = options.max_word_length) == null) {
    options.max_word_length = 16;
  }
  start = Date.now();
  end = start + options.duration;
  reader = new Stream;
  reader.readable = true;
  reader.resume = function() {
    var char, column, line, nb_chars, nb_words, _i, _j, _ref2, _ref3;
    reader.paused = false;
    while (!reader.paused && reader.readable) {
      if (Date.now() > end) {
        return reader.destroy();
      }
      line = [];
      for (nb_words = _i = 0, _ref2 = options.nb_columns; 0 <= _ref2 ? _i < _ref2 : _i > _ref2; nb_words = 0 <= _ref2 ? ++_i : --_i) {
        column = [];
        for (nb_chars = _j = 0, _ref3 = Math.ceil(Math.random() * options.max_word_length); 0 <= _ref3 ? _j < _ref3 : _j > _ref3; nb_chars = 0 <= _ref3 ? ++_j : --_j) {
          char = Math.floor(Math.random() * 32);
          column.push(String.fromCharCode(char + (char < 16 ? 65 : 97 - 16)));
        }
        line.push(column.join(''));
      }
      reader.emit('data', "" + (line.join(',')) + "\n");
    }
  };
  reader.pause = function() {
    return reader.paused = true;
  };
  reader.destroy = function() {
    reader.readable = false;
    reader.emit('end');
    return reader.emit('close');
  };
  if (options.start) {
    process.nextTick(reader.resume);
  }
  return reader;
};
