// Generated by CoffeeScript 1.4.0
var EventEmitter, Parser;

EventEmitter = require('events').EventEmitter;

/*

Parsing
=======

The library extend the [EventEmitter][event] and emit the following events:

*   *row*   
  Emitted by the parser on each line with the line content as an array of fields.
*   *end*   
  Emitted when no more data will be parsed.
*   *error*   
  Emitted when an error occured.
*/


Parser = function(csv) {
  this.csv = csv;
  this.options = csv.options.from;
  this.state = csv.state;
  this.quoting = false;
  this.lines = 0;
  return this;
};

Parser.prototype.__proto__ = EventEmitter.prototype;

/*

`parse(chars)`
--------------

Parse a string which may hold multiple lines.
Private state object is enriched on each character until 
transform is called on a new line.
*/


Parser.prototype.parse = function(chars) {
  var areNextCharsRowDelimiters, char, csv, escapeIsQuote, i, isEscape, isQuote, isReallyEscaped, l;
  csv = this.csv;
  chars = '' + chars;
  l = chars.length;
  i = 0;
  if (this.lines === 0 && csv.options.from.encoding === 'utf8' && 0xFEFF === chars.charCodeAt(0)) {
    i++;
  }
  while (i < l) {
    char = this.state.nextChar ? this.state.nextChar : chars.charAt(i);
    this.state.nextChar = chars.charAt(i + 1);
    if (!(this.options.rowDelimiter != null) && (this.state.nextChar === '\n' || this.state.nextChar === '\r')) {
      this.options.rowDelimiter = this.state.nextChar;
      if (this.state.nextChar === '\r' && chars.charAt(i + 2) === '\n') {
        this.options.rowDelimiter += '\n';
      }
    }
    if (char === this.options.escape || char === this.options.quote) {
      isReallyEscaped = false;
      if (char === this.options.escape) {
        escapeIsQuote = this.options.escape === this.options.quote;
        isEscape = this.state.nextChar === this.options.escape;
        isQuote = this.state.nextChar === this.options.quote;
        if (!(escapeIsQuote && !this.state.field && !this.quoting) && (isEscape || isQuote)) {
          i++;
          isReallyEscaped = true;
          char = this.state.nextChar;
          this.state.nextChar = chars.charAt(i + 1);
          this.state.field += char;
        }
      }
      if (!isReallyEscaped && char === this.options.quote) {
        if (this.quoting) {
          areNextCharsRowDelimiters = this.options.rowDelimiter && chars.substr(i + 1, this.options.rowDelimiter.length) === this.options.rowDelimiter;
          if (this.state.nextChar && !areNextCharsRowDelimiters && this.state.nextChar !== this.options.delimiter) {
            return this.error(new Error("Invalid closing quote at line " + (this.lines + 1) + "; found " + (JSON.stringify(this.state.nextChar)) + " instead of delimiter " + (JSON.stringify(this.options.delimiter))));
          }
          this.quoting = false;
        } else if (this.state.field) {
          this.state.field += char;
        } else {
          this.quoting = true;
        }
      }
    } else if (this.quoting) {
      this.state.field += char;
    } else if (char === this.options.delimiter) {
      if (this.options.trim || this.options.rtrim) {
        this.state.field = this.state.field.trimRight();
      }
      this.state.line.push(this.state.field);
      this.state.field = '';
    } else if (this.options.rowDelimiter && chars.substr(i, this.options.rowDelimiter.length) === this.options.rowDelimiter) {
      this.lines++;
      if (this.options.trim || this.options.rtrim) {
        this.state.field = this.state.field.trimRight();
      }
      this.state.line.push(this.state.field);
      this.state.field = '';
      this.emit('row', this.state.line);
      this.state.line = [];
      this.state.lastC = char;
      i += this.options.rowDelimiter.length;
      this.state.nextChar = chars.charAt(i);
      continue;
    } else if (char === ' ' || char === '\t') {
      if (!this.options.trim && !this.options.ltrim) {
        this.state.field += char;
      }
    } else {
      this.state.field += char;
    }
    this.state.lastC = char;
    i++;
  }
};

Parser.prototype.end = function() {
  if (this.quoting) {
    return this.error(new Error("Quoted field not terminated at line " + (this.lines + 1)));
  }
  if (this.state.field || this.state.lastC === this.options.delimiter || this.state.lastC === this.options.quote) {
    if (this.options.trim || this.options.rtrim) {
      this.state.field = this.state.field.trimRight();
    }
    this.state.line.push(this.state.field);
    this.state.field = '';
  }
  if (this.state.line.length > 0) {
    this.emit('row', this.state.line);
  }
  return this.emit('end', null);
};

Parser.prototype.error = function(e) {
  return this.emit('error', e);
};

module.exports = function(csv) {
  return new Parser(csv);
};

module.exports.Parser = Parser;

/*
[event]: http://nodejs.org/api/events.html
*/

