// Generated by CoffeeScript 1.3.3

module.exports = function() {
  return {
    count: 0,
    countWriten: 0,
    field: '',
    line: [],
    lastC: '',
    quoted: false,
    commented: false,
    buffer: null,
    bufferPosition: 0
  };
};
